changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - wontfix
      - dependencies
  categories:
    - title: 🚀 Features
      labels:
        - feature
    - title: 🔧 Enhancements
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🛠 Maintenance
      labels:
        - area:tests
        - github_actions
    - title: 📝 Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
